export HOME=/Users/danielmcninch

# Add Homebrew to PATH first
eval "$(/opt/homebrew/bin/brew shellenv)"

. $HOME/.asdf/asdf.sh

# XDG Base Directory
export XDG_CONFIG_HOME="$HOME/.config"

export LDFLAGS="-L$(brew --prefix openssl)/lib"
export CPPFlAGS="-I$(brew --prefix openssl)/include"
export CFLAGS="-I$(brew --prefix openssl)/include"

# If you come from bash you might have to change your $PATH.
PATH=$HOME/bin:/usr/local/bin:$HOME/.local/bin:$PATH
PATH="$(brew --prefix)/opt/grep/libexec/gnubin:$PATH"
export CPATH=/opt/homebrew/include 
export LIBRARY_PATH=/opt/homebrew/lib

# go
export GOPATH=$HOME/go
export GOROOT="$(brew --prefix golang)/libexec"
PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
export PATH="$PATH"
# deno
export DENO_INSTALL="/Users/danielmcninch/.deno"
PATH=$DENO_INSTALL/bin:$PATH
# racket
PATH="/Applications/Racket v8.7/bin:$PATH"
#love
PATH="/Applications/love_dir/:$PATH"
# haxe
export HAXE_STF_PATH="/opt/homebrew/lib/haxe/std"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export PATH
ZSH_THEME="robbyrussell"

# vcpkg
export CMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake

# FZF
export FZF_DEFAULT_COMMAND='fd --type file --hidden --no-ignore'
export GIT_PAGER='diff-so-fancy | less --tabs=4 -RFX'

plugins=(git brew macos ruby rails)

source $ZSH/oh-my-zsh.sh

# User configuration

export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
#export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconfig="mate ~/.zshrc"
alias ohmyzsh="mate ~/.oh-my-zsh"
alias vim="nvim"

source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# sad
export GIT_PAGER='diff-so-fancy | less --tabs=4 -RFX'

# Setting locale
LC_CTYPE=en_US.UTF-8
LC_ALL=en_US.UTF-8

# pnpm
export PNPM_HOME="/Users/danielmcninch/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
